In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
data1

[6, 7.5, 8, 0, 1]

In [3]:
# numpy를 이용하여 1차원 배열로 변형하기

arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [4]:
# 배열의 크기 확인
arr1.shape

(5,)

In [6]:
# 2차원 List
data2 = [
        [1,2,3,4],
        [5,6,7,8]
        ]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [7]:
# numpy로 2차원 배열로 변형하기
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
#  2행 4열 컬럼수 = 차원수
arr2.shape

(2, 4)

In [9]:
# 0으로 구성된 1차원 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# [page, row, column]
np.zeros([3,5,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [12]:
# 1로만 구성된 배열생성
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# 10 이라는 데이터로 5개 만들기
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# 숫자 8로 구성된 3행 5열 배열 생성
np.full((3,5), 8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [21]:
# 범위가 있는 배열 생성
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
arr1.dtype

dtype('float64')

In [23]:
arr3 = np.array([1,2,3,4,5], dtype=np.int64)
arr3.dtype

dtype('int64')

In [24]:
# data type을 변경
float_arr1 = arr3.astype(np.float64)
float_arr1.dtype

dtype('float64')

In [25]:
float_arr1

array([1., 2., 3., 4., 5.])

In [27]:
# 연산
arr1 = np.array((
                [1,2,3],
                [4,5,6]
                ), dtype=np.float64)

arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
arr2 = np.array((
                [7,8,9],
                [10,11,12]
                ), dtype=np.float64)

arr2

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [29]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [30]:
arr1 - arr2

array([[-6., -6., -6.],
       [-6., -6., -6.]])

In [31]:
arr1 * arr2

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [32]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [33]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [34]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
arr3 = 1 / arr1
arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr[5]

5

In [40]:
arr[5:9]

array([5, 6, 7, 8])

In [41]:
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[8:]

array([12,  9])

# 2차원 배열

In [44]:
arr2d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
arr2d.dtype

dtype('int64')

In [49]:
# 2번 행의 자료 출력
arr2d[2,:]

array([ 9, 10, 11, 12])

In [51]:
# 1에서 2번행의 자료 출력
arr2d[1:3,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
# 3번 열의 자료 출력
arr2d[:,3]

array([ 4,  8, 12, 16])

In [57]:
# 0, 1열의 자료 출력
arr2d[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [56]:
# 1행 2열의 자료 출력
arr2d[1,2]

7

In [62]:
arr2d[:2,1:3] = 0 

In [63]:
arr2d

array([[ 1,  0,  0,  4],
       [ 5,  0,  0,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---
# 난수 발생
- rand = 0부터 1사이의 균일 분포
- randn = 가우시안 표준 정규 분포
- randint : 균일 분포의 정수 난수

### Boolean Indexing

In [125]:
names = np.array(["Charles", "Kenny", "Hayoung", "Charles", "Hayoung", "Kenny", "Kenny"])
data = np.random.randn(7, 4)

In [126]:
names.shape

(7,)

In [127]:
data

array([[-1.73714162,  0.59828296,  0.0496232 ,  0.72341288],
       [-2.00168517,  0.63737675,  0.74322635,  0.60470309],
       [-0.6145577 , -2.68191628,  0.74633907,  1.12042773],
       [-0.78213777,  1.13192348, -1.02926725,  0.56528994],
       [ 1.01623108,  0.60121232,  0.3970951 , -1.33351697],
       [-0.02332235,  0.36998436, -0.15545663, -0.65053743],
       [ 0.85435792, -1.06602438,  0.20355162,  0.65024448]])

In [128]:
data.shape

(7, 4)

In [129]:
# Mask를 이용한 추출
names == "Charles"

array([ True, False, False,  True, False, False, False])

In [130]:
data[names == "Charles", :]

array([[-1.73714162,  0.59828296,  0.0496232 ,  0.72341288],
       [-0.78213777,  1.13192348, -1.02926725,  0.56528994]])

In [131]:
data[(names == "Charles") | (names == "Kenny"), :]

array([[-1.73714162,  0.59828296,  0.0496232 ,  0.72341288],
       [-2.00168517,  0.63737675,  0.74322635,  0.60470309],
       [-0.78213777,  1.13192348, -1.02926725,  0.56528994],
       [-0.02332235,  0.36998436, -0.15545663, -0.65053743],
       [ 0.85435792, -1.06602438,  0.20355162,  0.65024448]])

In [132]:
data[:]

array([[-1.73714162,  0.59828296,  0.0496232 ,  0.72341288],
       [-2.00168517,  0.63737675,  0.74322635,  0.60470309],
       [-0.6145577 , -2.68191628,  0.74633907,  1.12042773],
       [-0.78213777,  1.13192348, -1.02926725,  0.56528994],
       [ 1.01623108,  0.60121232,  0.3970951 , -1.33351697],
       [-0.02332235,  0.36998436, -0.15545663, -0.65053743],
       [ 0.85435792, -1.06602438,  0.20355162,  0.65024448]])

In [133]:
data[:,3]

array([ 0.72341288,  0.60470309,  1.12042773,  0.56528994, -1.33351697,
       -0.65053743,  0.65024448])

In [134]:
# data의 4번째 열 값중 0보다 작은 것의 mask만들기

data[data[:, 3] < 0,: ]

array([[ 1.01623108,  0.60121232,  0.3970951 , -1.33351697],
       [-0.02332235,  0.36998436, -0.15545663, -0.65053743]])

In [135]:
# data의 4번째 열의 값이 0보다 작은 data들을 0으로 대체하기

data[data[:, 3] < 0, :] = 0
data


array([[-1.73714162,  0.59828296,  0.0496232 ,  0.72341288],
       [-2.00168517,  0.63737675,  0.74322635,  0.60470309],
       [-0.6145577 , -2.68191628,  0.74633907,  1.12042773],
       [-0.78213777,  1.13192348, -1.02926725,  0.56528994],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.85435792, -1.06602438,  0.20355162,  0.65024448]])

In [136]:
# 정렬
arr = np.random.rand(8)
arr

array([0.57228013, 0.52081474, 0.65611332, 0.10857757, 0.81519019,
       0.75274968, 0.65545472, 0.29417273])

In [137]:
# 오름차순 정렬
np.sort(arr)

array([0.10857757, 0.29417273, 0.52081474, 0.57228013, 0.65545472,
       0.65611332, 0.75274968, 0.81519019])

In [138]:
# 내림차순 정렬
np.sort(arr)[::-1]

array([0.81519019, 0.75274968, 0.65611332, 0.65545472, 0.57228013,
       0.52081474, 0.29417273, 0.10857757])

In [139]:
arr = np.random.rand(5,3)
arr

array([[0.14120817, 0.04252573, 0.16016786],
       [0.07484858, 0.66997066, 0.51943932],
       [0.98683884, 0.99209318, 0.08984729],
       [0.87569523, 0.30754549, 0.79219206],
       [0.95177206, 0.46268298, 0.45162234]])

In [140]:
np.sort(arr, axis=0) # 0 : 열방향

array([[0.07484858, 0.04252573, 0.08984729],
       [0.14120817, 0.30754549, 0.16016786],
       [0.87569523, 0.46268298, 0.45162234],
       [0.95177206, 0.66997066, 0.51943932],
       [0.98683884, 0.99209318, 0.79219206]])

In [141]:
np.sort(arr, axis=1) # 1 : 행방향

array([[0.04252573, 0.14120817, 0.16016786],
       [0.07484858, 0.51943932, 0.66997066],
       [0.08984729, 0.98683884, 0.99209318],
       [0.30754549, 0.79219206, 0.87569523],
       [0.45162234, 0.46268298, 0.95177206]])

In [152]:
# np.sort(arr, axis=0)[::-1]
np.sort(arr, axis=1)[:,::-1]

array([[0.16016786, 0.14120817, 0.04252573],
       [0.66997066, 0.51943932, 0.07484858],
       [0.99209318, 0.98683884, 0.08984729],
       [0.87569523, 0.79219206, 0.30754549],
       [0.95177206, 0.46268298, 0.45162234]])

In [153]:
# 중복제거
np.unique(names)

array(['Charles', 'Hayoung', 'Kenny'], dtype='<U7')

---
# reshape***

In [155]:
# reshape가 제일 중요
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [157]:
# 2차원 배열로 변경
arr1 = np.reshape(arr, (2,4))
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [158]:
# 3차원 배열로 변경
arr2 = np.reshape(arr, [2,2,2])
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [159]:
# 2차원 배열을 1차원으로 변경
arr3 = arr1.reshape(-1, 1)  # 데이터 개수를 정할 수 없을 때 -1 사용
arr3                        # 딥러닝에서는 1을 표현

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [161]:
arr4 = arr2.reshape(-1)
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [162]:
# 단위행렬 : 
arr3 == arr4

array([[ True, False, False, False, False, False, False, False],
       [False,  True, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False, False, False, False,  True, False],
       [False, False, False, False, False, False, False,  True]])